' Preview durch <Alt>d
' https://plantuml.com/de/state-diagram
' https://plantuml.com/de/guide

@startuml Zustandsdiagramm

hide empty description

state index.html {
    index.html: jwt
    index.html: roles
    index.html: expiration

    [*] --> Home: Logout

    state SucheKunden {
        [*] --> Suchformular: Suchkriterien eingeben
        Suchformular --> Waiting: Button "Suchen"
        state SuchergebnisChoice <<choice>>
        Waiting --> SuchergebnisChoice: Suchergebnis eingetroffen

        state Suchergebnis {
            SuchergebnisChoice --> GefundeneKunden: mind. 1 Kunde\n gefunden
            SuchergebnisChoice --> ErrorMessage: kein Kunde\n gefunden

            ErrorMessage -right[hidden]-> GefundeneKunden
        }
    }
    [*] -down-> SucheKunden: Menüpunkt "Suche"
    GefundeneKunden -right-> DetailsKunde: Link anklicken

    [*] -down-> CreateKunde: Menüpunkt "Neues Kunde"
    SucheKunden -right[hidden]-> CreateKunde
    state CreateChoice <<choice>>
    CreateKunde --> CreateChoice: Button "OK"
    CreateChoice --> CreateKunde: fehlerhafte Daten
    CreateChoice --> DetailsKunde: korrekte Daten

    DetailsKunde -right-> UpdateKunde: Button "Bearbeiten"
    state UpdateChoice <<choice>>
    UpdateKunde -up-> UpdateChoice: Button "OK"
    UpdateChoice --> UpdateKunde: fehlerhafte Daten
    UpdateChoice --> DetailsKunde: korrekte Daten
}

@enduml
