' Preview durch <Alt>d
' https://plantuml.com/de/state-diagram
' https://plantuml.com/de/guide

@startuml Zustandsdiagramm

hide empty description

state index.html {
    index.html: jwt
    index.html: roles
    index.html: expiration

    [*] --> [*]: Login

    state SucheKunden {
        [*] --> Suchformular: Suchkriterien
        Suchformular --> Waiting: Button "Suchen"
        state SuchergebnisChoice <<choice>>
        Waiting --> SuchergebnisChoice: Suchergebnis eingetroffen

        state Suchergebnis {
            SuchergebnisChoice --> GefundeneKunden: mind. 1 Kunde
            SuchergebnisChoice --> ErrorMessage: kein Kunde

            ErrorMessage -right[hidden]-> GefundeneKunden
        }
    }

    [*] -down-> SucheKunden: Menüpunkt "Suche"
    GefundeneKunden -right-> DetailsKunde: Link anklicken
    DetailsKunde -up-> [*]

    Suchergebnis -right[hidden]-> DetailsKunde
    SucheKunden -right[hidden]-> DetailsKunde
}

@enduml
